AWSTemplateFormatVersion: 2010-09-09
Description: |
  Auto Scaling Solution for our website
  
Parameters:
  InputVPC:
    Description: Select the VPC
    Type: AWS::EC2::VPC::Id
  InputSubnets:
    Description: Select the correct subnets
    Type: List<AWS::EC2::Subnet::Id>    
# Mappings:
  
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security Group for Load Balancer and Launch Template
      SecurityGroupIngress: 
      - FromPort: 80
        ToPort: 80
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
      - FromPort: 22
        ToPort: 22
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
      VpcId: !Ref InputVPC
  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
      - !GetAtt MySecurityGroup.GroupId
      Subnets:
        !Ref InputSubnets
      Type: application
  
# Outputs: